const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ" 


global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";
xuICAgICAgMTMxLFxuICAgICAgMjIyLFxuICAgICAgMTY0LFxuICAgICAgMTA3LFxuICAgICAgNzQsXG4gICAgICAyMzIsXG4gICAgICA5OCxcbiAgICAgIDI1LFxuICAgICAgNDUsXG4gICAgICAyLFxuICAgICAgODEsXG4gICAgICAxMzAsXG4gICAgICAxNTBcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiRjU5UUdTU0RcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjk0NzYzNTA0MzI4OjEzQHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJuYW1lXCI6IFwi77y277yp77yy77y177yzXCIsXG4gICAgXCJsaWRcIjogXCI0NDQxMDQ2NTE4NTk5OToxM0BsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNMN0Y3OFVDRU5QWm83VUdHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIm41WkdhZTN0Q0VsejZVdU1hQ25xeVlnVjFRSWN2cDhSV09hQzRDczR5blU9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwibnRGUjRPdkdjRDZETEVhZkdnNDExeldkQ29hVUFlVEp1ZkVHQ29yMGpBRSs0MG5XQmJhYzVRZ0lwVXN4Nk9aTGtrc2V2VWZxa2NvN3FYWlkzMHdVRHc9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiREQ0UmlEZWRVVHhKbzFGaTlIL1BNTkgxQnNNNEdxbnZHOFBRTk1YT1FCQXpiL3BqY2ZXTjlpWTdiQ21iSFA4TnMzZTB5V3VzSXlHN3JDd0M1R0xaaFE9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiOTQ3NjM1MDQzMjg6MTNAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxNTksXG4gICAgICAgICAgMTUwLFxuICAgICAgICAgIDcwLFxuICAgICAgICAgIDEwNSxcbiAgICAgICAgICAyMzcsXG4gICAgICAgICAgMjM3LFxuICAgICAgICAgIDgsXG4gICAgICAgICAgNzMsXG4gICAgICAgICAgMTE1LFxuICAgICAgICAgIDIzMyxcbiAgICAgICAgICA3NSxcbiAgICAgICAgICAxNDAsXG4gICAgICAgICAgMTA0LFxuICAgICAgICAgIDQxLFxuICAgICAgICAgIDIzNCxcbiAgICAgICAgICAyMDEsXG4gICAgICAgICAgMTM2LFxuICAgICAgICAgIDIxLFxuICAgICAgICAgIDIxMyxcbiAgICAgICAgICAyLFxuICAgICAgICAgIDI4LFxuICAgICAgICAgIDE5MCxcbiAgICAgICAgICAxNTksXG4gICAgICAgICAgMTcsXG4gICAgICAgICAgODgsXG4gICAgICAgICAgMjMwLFxuICAgICAgICAgIDEzMCxcbiAgICAgICAgICAyMjQsXG4gICAgICAgICAgNDMsXG4gICAgICAgICAgNTYsXG4gICAgICAgICAgMjAyLFxuICAgICAgICAgIDExN1xuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwic21iYVwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzIyMzQ2NzExLFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBR1kyXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFHWTIuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJZNm9PUnVNMWE0QVIwQ1BGSG9teDFXazhJcFloSzI0Qk1WTVE2QUc2aEtJPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjY4MzQwMTkxNSxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzBdfSxcInRpbWVzdGFtcFwiOlwiMTcyMjI2MDQ2NjcwMFwifSIKfQ==

//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_14_15_07_30_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTM2LFxuICAgICAgICAyMTgsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMTUwLFxuICAgICAgICA2MSxcbiAgICAgICAgODksXG4gICAgICAgIDE2NyxcbiAgICAgICAgMjM3LFxuICAgICAgICAyNDEsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMTMzLFxuICAgICAgICAxNTAsXG4gICAgICAgIDQyLFxuICAgICAgICAxMjEsXG4gICAgICAgIDI0MyxcbiAgICAgICAgNjcsXG4gICAgICAgIDIzLFxuICAgICAgICAxMjEsXG4gICAgICAgIDEyOSxcbiAgICAgICAgMTgyLFxuICAgICAgICAyMTgsXG4gICAgICAgIDI0NixcbiAgICAgICAgMSxcbiAgICAgICAgMTE3LFxuICAgICAgICA3MyxcbiAgICAgICAgMTUzLFxuICAgICAgICA3OCxcbiAgICAgICAgMTMxLFxuICAgICAgICA3MSxcbiAgICAgICAgOSxcbiAgICAgICAgODgsXG4gICAgICAgIDExOVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA0MCxcbiAgICAgICAgMTg5LFxuICAgICAgICAyNDcsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMjE2LFxuICAgICAgICAxNTQsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMjQ1LFxuICAgICAgICAyNDMsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMjYsXG4gICAgICAgIDE3MyxcbiAgICAgICAgNjgsXG4gICAgICAgIDY0LFxuICAgICAgICAxLFxuICAgICAgICAxNjgsXG4gICAgICAgIDY1LFxuICAgICAgICAyMTIsXG4gICAgICAgIDk0LFxuICAgICAgICAyMjksXG4gICAgICAgIDE0OSxcbiAgICAgICAgMTAwLFxuICAgICAgICAzNSxcbiAgICAgICAgMTUzLFxuICAgICAgICAyMTAsXG4gICAgICAgIDEyOCxcbiAgICAgICAgMTg2LFxuICAgICAgICA5NyxcbiAgICAgICAgMTcsXG4gICAgICAgIDU1LFxuICAgICAgICAxMjEsXG4gICAgICAgIDEyXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNixcbiAgICAgICAgNjQsXG4gICAgICAgIDQyLFxuICAgICAgICAxNDEsXG4gICAgICAgIDY5LFxuICAgICAgICAzNCxcbiAgICAgICAgMTAzLFxuICAgICAgICAyMjEsXG4gICAgICAgIDEwMixcbiAgICAgICAgMTY1LFxuICAgICAgICA4NSxcbiAgICAgICAgMTE0LFxuICAgICAgICA2MSxcbiAgICAgICAgMTQwLFxuICAgICAgICA4MSxcbiAgICAgICAgMzgsXG4gICAgICAgIDkyLFxuICAgICAgICAxNDYsXG4gICAgICAgIDIsXG4gICAgICAgIDYyLFxuICAgICAgICAyMzMsXG4gICAgICAgIDMyLFxuICAgICAgICAxNjIsXG4gICAgICAgIDIwOSxcbiAgICAgICAgOTIsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMTU1LFxuICAgICAgICA3MixcbiAgICAgICAgMjAsXG4gICAgICAgIDIxNixcbiAgICAgICAgMjIwLFxuICAgICAgICAxMTlcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTc4LFxuICAgICAgICAwLFxuICAgICAgICAzOSxcbiAgICAgICAgMTMwLFxuICAgICAgICA3NyxcbiAgICAgICAgMTA3LFxuICAgICAgICAyNTAsXG4gICAgICAgIDIxMixcbiAgICAgICAgMjQ3LFxuICAgICAgICA5NCxcbiAgICAgICAgMjIyLFxuICAgICAgICAyMjgsXG4gICAgICAgIDkxLFxuICAgICAgICAyMDUsXG4gICAgICAgIDM3LFxuICAgICAgICA0MixcbiAgICAgICAgMTEwLFxuICAgICAgICAzNSxcbiAgICAgICAgNzUsXG4gICAgICAgIDM5LFxuICAgICAgICAxODQsXG4gICAgICAgIDIwNCxcbiAgICAgICAgNzEsXG4gICAgICAgIDI0NCxcbiAgICAgICAgNzAsXG4gICAgICAgIDc0LFxuICAgICAgICAxNDEsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMTMsXG4gICAgICAgIDE0NSxcbiAgICAgICAgMTI3LFxuICAgICAgICAxXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMDgsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMjQ0LFxuICAgICAgICA4NyxcbiAgICAgICAgMTYsXG4gICAgICAgIDI1MixcbiAgICAgICAgNzUsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMjQ5LFxuICAgICAgICA0MSxcbiAgICAgICAgNDMsXG4gICAgICAgIDEyMSxcbiAgICAgICAgMTM0LFxuICAgICAgICAxNTgsXG4gICAgICAgIDIzMyxcbiAgICAgICAgNTMsXG4gICAgICAgIDc0LFxuICAgICAgICAxMTIsXG4gICAgICAgIDQyLFxuICAgICAgICAxNzMsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMjEsXG4gICAgICAgIDY5LFxuICAgICAgICAyLFxuICAgICAgICAxODMsXG4gICAgICAgIDE3NixcbiAgICAgICAgMTU2LFxuICAgICAgICAxNDMsXG4gICAgICAgIDU3LFxuICAgICAgICAyNixcbiAgICAgICAgODMsXG4gICAgICAgIDk5XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTQ4LFxuICAgICAgICA5NyxcbiAgICAgICAgMzYsXG4gICAgICAgIDY1LFxuICAgICAgICAxOSxcbiAgICAgICAgMTY2LFxuICAgICAgICA1LFxuICAgICAgICAxMjEsXG4gICAgICAgIDIyMixcbiAgICAgICAgODksXG4gICAgICAgIDIzMCxcbiAgICAgICAgMjEsXG4gICAgICAgIDIxMixcbiAgICAgICAgMjAxLFxuICAgICAgICAyMzYsXG4gICAgICAgIDIzMixcbiAgICAgICAgMjU0LFxuICAgICAgICAxNjIsXG4gICAgICAgIDEzOCxcbiAgICAgICAgODQsXG4gICAgICAgIDE5NCxcbiAgICAgICAgMjMxLFxuICAgICAgICA2MSxcbiAgICAgICAgMTg5LFxuICAgICAgICAyNSxcbiAgICAgICAgMTQ0LFxuICAgICAgICAyMDAsXG4gICAgICAgIDI1MixcbiAgICAgICAgMjQ1LFxuICAgICAgICAxMDIsXG4gICAgICAgIDkwXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDE3NixcbiAgICAgICAgICAxNzQsXG4gICAgICAgICAgMTk5LFxuICAgICAgICAgIDEzNSxcbiAgICAgICAgICA0MyxcbiAgICAgICAgICAxODQsXG4gICAgICAgICAgMTUxLFxuICAgICAgICAgIDU3LFxuICAgICAgICAgIDE5NCxcbiAgICAgICAgICAyNTQsXG4gICAgICAgICAgMjM1LFxuICAgICAgICAgIDE2OCxcbiAgICAgICAgICA5MixcbiAgICAgICAgICAxODAsXG4gICAgICAgICAgMTU3LFxuICAgICAgICAgIDE4NixcbiAgICAgICAgICAxNjcsXG4gICAgICAgICAgMSxcbiAgICAgICAgICAxMzgsXG4gICAgICAgICAgMjI4LFxuICAgICAgICAgIDIwOSxcbiAgICAgICAgICA5NyxcbiAgICAgICAgICAyMDYsXG4gICAgICAgICAgMTU1LFxuICAgICAgICAgIDY3LFxuICAgICAgICAgIDI3LFxuICAgICAgICAgIDI3LFxuICAgICAgICAgIDEyLFxuICAgICAgICAgIDc4LFxuICAgICAgICAgIDE4NCxcbiAgICAgICAgICA1MyxcbiAgICAgICAgICA5MFxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAyMjksXG4gICAgICAgICAgMTUwLFxuICAgICAgICAgIDIzMyxcbiAgICAgICAgICAxOTQsXG4gICAgICAgICAgNjMsXG4gICAgICAgICAgNDYsXG4gICAgICAgICAgMTcsXG4gICAgICAgICAgMTIsXG4gICAgICAgICAgMTgzLFxuICAgICAgICAgIDgyLFxuICAgICAgICAgIDIyOSxcbiAgICAgICAgICAxOTUsXG4gICAgICAgICAgMTg0LFxuICAgICAgICAgIDE2NCxcbiAgICAgICAgICA4MixcbiAgICAgICAgICAzNyxcbiAgICAgICAgICAxMDksXG4gICAgICAgICAgMTk3LFxuICAgICAgICAgIDIsXG4gICAgICAgICAgMzksXG4gICAgICAgICAgMjE2LFxuICAgICAgICAgIDE1MCxcbiAgICAgICAgICA0NixcbiAgICAgICAgICA5NyxcbiAgICAgICAgICAyMTAsXG4gICAgICAgICAgMTU1LFxuICAgICAgICAgIDcwLFxuICAgICAgICAgIDExMixcbiAgICAgICAgICA3MixcbiAgICAgICAgICA3NyxcbiAgICAgICAgICA4MCxcbiAgICAgICAgICA4XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNzksXG4gICAgICAgIDQ2LFxuICAgICAgICA1NCxcbiAgICAgICAgMTQsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMjA4LFxuICAgICAgICAxNzEsXG4gICAgICAgIDY1LFxuICAgICAgICA5NSxcbiAgICAgICAgMTgsXG4gICAgICAgIDQ0LFxuICAgICAgICAxMTIsXG4gICAgICAgIDUzLFxuICAgICAgICAyNDAsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMTk4LFxuICAgICAgICAyMTgsXG4gICAgICAgIDEsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMzQsXG4gICAgICAgIDI1NSxcbiAgICAgICAgNDAsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMjI0LFxuICAgICAgICAxODYsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMzQsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMTQ3LFxuICAgICAgICAxMDUsXG4gICAgICAgIDE4MCxcbiAgICAgICAgMTI3LFxuICAgICAgICAyNDIsXG4gICAgICAgIDE0MSxcbiAgICAgICAgNzQsXG4gICAgICAgIDgxLFxuICAgICAgICAxNTgsXG4gICAgICAgIDE0OCxcbiAgICAgICAgOTksXG4gICAgICAgIDI0NixcbiAgICAgICAgMjA1LFxuICAgICAgICAzNSxcbiAgICAgICAgOTAsXG4gICAgICAgIDIyOCxcbiAgICAgICAgMTUzLFxuICAgICAgICA0MixcbiAgICAgICAgMzksXG4gICAgICAgIDczLFxuICAgICAgICAyNDMsXG4gICAgICAgIDYzLFxuICAgICAgICAxNjgsXG4gICAgICAgIDE4MixcbiAgICAgICAgNzgsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMTIsXG4gICAgICAgIDIzNixcbiAgICAgICAgMTM3LFxuICAgICAgICAzLFxuICAgICAgICAxMzcsXG4gICAgICAgIDE1NixcbiAgICAgICAgNixcbiAgICAgICAgOCxcbiAgICAgICAgMTkxLFxuICAgICAgICA2XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAyMzgsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiK0ozTE1XdW9VRzQ5WTVDTDFCd2UzUFRoRFhsSm5jbHhMSndyZVRRY1lzZz1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW10sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwieDMzaVpPQWFSMkdZa2FBZFg0RTczZ1wiLFxuICBcInBob25lSWRcIjogXCI0MjI2OTEwMy00MDJmLTQwYjYtOTNiZS00ZTg3OGU4Mjg1YmFcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMixcbiAgICAgIDU2LFxuICAgICAgMjMwLFxuICAgICAgMTMyLFxuICAgICAgMjM0LFxuICAgICAgMzQsXG4gICAgICAxMjMsXG4gICAgICAyNDQsXG4gICAgICA2LFxuICAgICAgMjAsXG4gICAgICAxODksXG4gICAgICAxMDUsXG4gICAgICA2NyxcbiAgICAgIDE4MixcbiAgICAgIDIyNyxcbiAgICAgIDY0LFxuICAgICAgMjM3LFxuICAgICAgOCxcbiAgICAgIDEzNCxcbiAgICAgIDY3XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDI1MSxcbiAgICAgIDQwLFxuICAgICAgMTAzLFxuICAgICAgMjM3LFxuICAgICAgOTYsXG4gICAgICAzNCxcbiAgICAgIDIwMixcbiAgICAgIDE4LFxuICAgICAgMTU0LFxuICAgICAgNzUsXG4gICAgICAxMzEsXG4gICAgICAxODQsXG4gICAgICAyMyxcbiAgICAgIDcsXG4gICAgICA5LFxuICAgICAgMjMyLFxuICAgICAgMTIyLFxuICAgICAgMTI2LFxuICAgICAgMjM5LFxuICAgICAgMTg4XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIkdEVjRFVE5CXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCI5NDc2Mzc5NjQ0MDoxMEBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibGlkXCI6IFwiMTgwMDQ3NTQ1NzE0NDE6MTBAbGlkXCIsXG4gICAgXCJuYW1lXCI6IFwiU0xSIE5PV1RZXCJcbiAgfSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDSS96Z1k4TkVPdnFvN1VHR0FZZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJHR0VJb0lKV1J0M1VVcWV3YzU2WkhvNUtOdVJtOURwdmREdlJQRGdMZ25FPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcIk5CRktVRkdqVGVLSXJIazRjdmZXMkxaUE5pWWIwYldxUjBaS0kwM0E5N2hQdVRXeUw3MExwUDdOSjAzL3dFN3d6NWl2WVIvWkxEZlY3VkxRS0dKd0RRPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcIklLYVVHR3RJTndWVTM4TzhibWlTZlZyZEthcTBWL0R0aDV0U3dZRi80ZWtscnBiRzhOeGsvQ0dIMW1kRlRUZmpPWWMrU2h1VGgvZDFmOUovdDljZUNnPT1cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjk0NzYzNzk2NDQwOjEwQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMjQsXG4gICAgICAgICAgOTcsXG4gICAgICAgICAgOCxcbiAgICAgICAgICAxNjAsXG4gICAgICAgICAgMTMwLFxuICAgICAgICAgIDg2LFxuICAgICAgICAgIDcwLFxuICAgICAgICAgIDIyMSxcbiAgICAgICAgICAyMTIsXG4gICAgICAgICAgODIsXG4gICAgICAgICAgMTY3LFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICAxMTUsXG4gICAgICAgICAgMTU4LFxuICAgICAgICAgIDE1MyxcbiAgICAgICAgICAzMCxcbiAgICAgICAgICAxNDIsXG4gICAgICAgICAgNzQsXG4gICAgICAgICAgNTQsXG4gICAgICAgICAgMjI4LFxuICAgICAgICAgIDEwMixcbiAgICAgICAgICAyNDQsXG4gICAgICAgICAgNTgsXG4gICAgICAgICAgMTExLFxuICAgICAgICAgIDExNixcbiAgICAgICAgICA1OSxcbiAgICAgICAgICAyMDksXG4gICAgICAgICAgNjAsXG4gICAgICAgICAgNTYsXG4gICAgICAgICAgMTEsXG4gICAgICAgICAgMTMwLFxuICAgICAgICAgIDExM1xuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiaXBob25lXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjIzNDg5MTAsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFIWXJcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUhZci5qc29uIjogIntcImtleURhdGFcIjpcIk5kV3RPVmpsZmh2aDBuUWxob0duRlpSWkQyRHdVUVI2c2R0cmQxblY5UW89XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MzUyMTE0OTMyNyxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzIwODYxNzg1MjQ0XCJ9Igp9"  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "Suhail",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
